PROG=main.exe
CC=gcc
CFLAGS=-g -Wall -Werror
DEPS = safeinput.h shapes.h calculator.h
OBJ = main.o safeinput.o shapes.o calculator.o
 
%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)
 
$(PROG): $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)